spring.application.name=spring-data-jpa

# Connection Details
spring.datasource.url=jdbc:mysql://localhost:3306/spring_jpa_api
spring.datasource.username=productAdmin
spring.datasource.password=admin123*

# Driver Class (Optional in newer Spring Boot versions as it's auto-detected)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

